version: '3.8'

services:

  api:
    build: 
      dockerfile: ./Dockerfile
      context: ./backend/
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=druckerdienst
      - POSTGRES_PASS=secret
      - POSTGRES_DB=druckerdienst
    ports:
      - "3000:3000"

  db:
    image: postgres
    restart: always
    environment:
        - POSTGRES_USER=druckerdienst
        - POSTGRES_PASSWORD=secret
        - POSTGRES_DB=druckerdienst
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    environment:
     - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
     - PGADMIN_DEFAULT_PASSWORD=secret
    ports:
     - "5050:80"
    restart: always

volumes:
  database-data:
  pgadmin: